name: Manual Workflow

on:
  workflow_dispatch:
    branches:
      - main
      - aamirgo-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired workflow steps here

      - name: Build
        run: |
          echo "Building the project..."
          # Add build commands here

      - name: Test
        run: |
          echo "Running tests..."
          # Add test commands here

      # Add additional steps as needed
